### ISSUE TITLE
Ensure Nested Collection (Collection<Collection<X>>) mapping works

### ISSUE THREAD

**Issue by slemesle** [slemesle/selma#5]

**Comment by shakahub** [comment]
Is there any examples of deep nested List of List mappings ?

**Comment by slemesle** [comment]
Hi the project has moved to https://github.com/xebia-france/selma we also have a site on http://selma-java.org 

Now for the question yes we have a sample that you can find in test sources : 
https://github.com/xebia-france/selma/blob/master/processor/src/test/java/fr/xebia/extras/selma/it/mappers/NestedMapAndCollectionMapper.java
